when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
      faker:
        locale: fr_FR
      make_factory:

        # Default namespace where factories will be created by maker.
        default_namespace:    DataFixtures\Factory
      make_story:

        # Default namespace where stories will be created by maker.
        default_namespace:    DataFixtures\Story

when@test: *dev
